Repository VuehappyJob20241219/octfair2, pull requests merged in 2025-01, with the labels that each got.

#88 기업회원관리 tanstack query 적용 및 메서드 모듈화
  src/api/api.js
  src/api/manageUser/applicantDetailUpdateApi.js
  src/api/manageUser/bizDetailSearchApi.js
  src/api/manageUser/bizDetailUpdateApi.js
  src/api/manageUser/bizListSearchApi.js
  src/components/page/ManageUser/Biz/BizMain.vue
  src/components/page/ManageUser/Biz/BizModal.vue
  src/components/page/ManageUser/Biz/BizSearch.vue
  src/hook/manageUser/useBizDetailSearchQuery.js
  src/hook/manageUser/useBizDetailUpdateMutation.js
  src/hook/manageUser/useBizListSearchQuery.js
  src/views/ManageUser/ManageBiz.vue
Labels: enhancement

#90 개인회원관리, 기업회원관리 update 안되는 오류 해결
  src/api/manageUser/applicantDetailUpdateApi.js
  src/api/manageUser/bizDetailUpdateApi.js
  src/components/page/ManageUser/Applicant/ApplicantMain.vue
  src/components/page/ManageUser/Biz/BizMain.vue
  src/hook/manageUser/useApplicantDetailUpdateMutation.js
  src/hook/manageUser/useApplicantListSearchQuery.js
  src/hook/manageUser/useBizDetailUpdateMutation.js
  src/hook/manageUser/useBizListSearchQuery.js
  vite.config.js
Labels: bug

#93 feat:#92 스크랩 페이지 1차 저장
  components.d.ts
  src/api/jobs/scrapListSearchApi.js
  src/components/page/Jobs/Scrap/ScrapMain.vue
  src/components/page/Jobs/Scrap/ScrapSearch.vue
  src/hook/jobs/useScrapListSearchQuery.js
  src/router/index.js
  src/views/Jobs/Scrap.vue
Labels: enhancement

#96 공고보기에서 공고수정하기 연결
  src/components/page/Hire/HirePostEditor.vue
  src/components/page/Jobs/Post/PostDetail.vue
  src/router/index.js
Labels: enhancement

#101 feat:#85 입사 지원 모달 개발 및 공고 detail 파일 다운로드 추가
  src/components/page/Jobs/Post/PostApplyModal.vue
  src/components/page/Jobs/Post/PostDetail.vue
Labels: enhancement

#105 Feat/#104 메뉴 창의 반응형UI의 작동/디자인이 익히 봐온 일반적 작동/형태 되도록 개선
  DB 테이블생성코드 (백업용).txt
  components.d.ts
  index.html
  src/api/apply/resume/resumeDetailUpdateApi.js
  src/assets/newyear.gif
  src/assets/styles/global.css
  src/components/layout/AddOn.vue
  src/components/layout/AddOnPack/LunchMenu.vue
  src/components/layout/AddOnPack/MusicBox.vue
  src/components/layout/LeftManuBar.vue
  src/components/page/Apply/Resume/InnerPage/CareerList.vue
  src/components/page/Apply/Resume/InnerPage/CertList.vue
  src/components/page/Apply/Resume/InnerPage/EduList.vue
  src/components/page/Apply/Resume/InnerPage/SkillList.vue
  src/components/page/Apply/Resume/ResumeDetail.vue
  src/components/page/Apply/Resume/ResumeMain.vue
  src/components/page/Apply/Resume/ResumeStyle.css
  src/views/DashBoard/DashBoard.vue
Labels: enhancement

#106 feat/#103 공고 editor css 수정
  src/components/page/Hire/HirePostEditor.vue
Labels: enhancement

#110 feat/#82 회원정보 수정 작업중
  components.d.ts
  package-lock.json
  package.json
  src/api/api.js
  src/api/login/findIdApi.js
  src/api/login/findPwdApi.js
  src/api/login/findPwdUpdateApi.js
  src/api/login/signUpApi.js
  src/api/login/signUpIdCheckApi.js
  src/api/mypage/getUserInfoApi.js
  src/api/mypage/updatePwdApi.js
  src/api/mypage/updateUserApi.js
  src/components/page/Login/FindIdModal.vue
  src/components/page/Login/FindPwdModal.vue
  src/components/page/Login/SignUpModal.vue
  src/components/page/MyPage/MyPageMain.vue
  src/components/page/MyPage/UpdatePwdModal.vue
  src/components/page/MyPage/WithdrawMain.vue
  src/hook/Login/useFindId.js
  src/hook/Login/useFindPwd.js
  src/hook/Login/useFindPwdUpdate.js
  src/hook/Login/useSignUp.js
  src/hook/Login/useSignUpIdCheck.js
  src/hook/mypage/useGetUserInfo.js
  src/hook/mypage/useUpdatePwd.js
  src/hook/mypage/useUpdateUser.js
  src/router/index.js
  src/views/MyPage/MyPage.vue
  src/views/MyPage/Withdraw.vue
Labels: enhancement

#117 사라진 코드 재추가
  components.d.ts
  src/api/manageUser/applicantDetailSearchApi.js
  src/api/manageUser/applicantDetailUpdateApi.js
  src/api/manageUser/applicantListSearchApi.js
  src/api/manageUser/applicantPwResetApi.js
  src/hook/manageUser/useApplicantDetailSearchQuery.js
  src/router/index.js
Labels: bug

#118 파일명 수정
  src/api/faq/faqListSearchApi.js
Labels: bug

#120 feat:#114 스크랩 페이지
  src/components/page/Jobs/Post/PostApplyModal.vue
  src/components/page/Jobs/Post/PostDetail.vue
  src/components/page/Jobs/Post/PostMain.vue
  src/components/page/Jobs/Post/PostSearch.vue
  src/components/page/Jobs/Scrap/ScrapMain.vue
  src/components/page/Jobs/Scrap/ScrapSearch.vue
  src/router/index.js
  src/views/Jobs/Scrap.vue
Labels: enhancement

#122 feat/#82 마이페이지 비밀번호 변경 기능
  package-lock.json
  src/api/login/findIdApi.js
  src/api/login/signUpApi.js
  src/api/login/signUpIdCheckApi.js
  src/api/mypage/getUserInfoApi.js
  src/api/mypage/updatePwdApi.js
  src/api/mypage/updateUserApi.js
  src/components/page/Login/SignUpModal.vue
  src/components/page/MyPage/MyPageMain.vue
  src/components/page/MyPage/UpdatePwdModal.vue
  src/components/page/MyPage/WithdrawMain.vue
  src/hook/Login/useFindPwdUpdate.js
  src/hook/Login/useSignUp.js
  src/hook/mypage/useGetUserInfo.js
  src/hook/mypage/useUpdatePwd.js
  src/hook/mypage/useUpdateUser.js
Labels: enhancement

#128 개인회원관리, 기업회원관리 정보 수정시 에러 해결
  src/components/page/ManageUser/Applicant/ApplicantModal.vue
  src/hook/manageUser/useApplicantDetailUpdateMutation.js
  src/hook/manageUser/useBizDetailUpdateMutation.js
Labels: bug

#129 feat:#114 공고 detail 새로고침 안 되는 문제 수정
  src/components/page/Jobs/Post/PostDetail.vue
Labels: bug

#133 fix/#132 지원하기 modal 중복으로 뜨는 문제 수정
  src/components/page/Jobs/Post/PostApplyModal.vue
  src/components/page/Jobs/Post/PostDetail.vue
Labels: bug

#135 fix/#134 공고 Detail에서 페이지 이동 시 400 에러 뜨는 거 수정
  src/components/page/Jobs/Post/PostDetail.vue
Labels: bug

#136 feat:#124 스크랩 페이지 radio에서 checkbox로 변경
  src/components/page/Jobs/Post/PostDetail.vue
  src/components/page/Jobs/Scrap/ScrapMain.vue
  src/components/page/Jobs/Scrap/ScrapSearch.vue
  삭제해도됨.txt
  테스트용파일입니다123123.txt
Labels: enhancement

#138 fix/#137 페이지 새로고침 문제 및 일부 수정
  src/components/page/Approval/ApprovalPostMain.vue
  src/components/page/Approval/ConfirmedPostMain.vue
  src/components/page/Jobs/Post/PostDetail.vue
  src/components/page/Jobs/Post/PostMain.vue
  src/components/page/Jobs/Scrap/ScrapMain.vue
  src/components/page/Jobs/Scrap/ScrapSearch.vue
  src/hook/approval/useApprovalListSearchQuery.js
  src/hook/jobs/usePostListSearchQuery.js
  src/hook/jobs/useScrapListSearchQuery.js
  src/router/index.js
  src/views/Jobs/Scrap.vue
Labels: bug

#140 회원탈퇴 페이지 구현
  components.d.ts
  package-lock.json
  package.json
  src/api/Withdraw/WithdrawApi.js
  src/api/api.js
  src/api/mypage/deleteUserApi.js
  src/components/page/MyPage/WithdrawMain.vue
  src/components/page/MyPage/WithdrawModal.vue
  src/components/page/WithdrawDetail/WithdrawDetail.vue
  src/hook/Withdraw/useWithdrawMutation.js
  src/hook/mypage/useUserDeleteMutation.js
  src/views/MyPage/Withdraw.vue
Labels: enhancement

#147 fix:#146 수정버튼 클릭시 route idx 변동에 반응하게 수정
  src/components/page/Hire/HirePostEditor.vue
  src/views/Withdraw/Withdraw.vue
Labels: bug

#149 fix:#148 공고 수정시 승인 여부 대기중으로 변경, 승인된 공고는 수정 불가하게 변경
  src/components/page/Hire/HirePostEditor.vue
  src/components/page/Jobs/Post/PostDetail.vue
Labels: bug

#151 fix/#150 공고 detail 삭제 안 되는 문제 수정
  src/components/page/Jobs/Post/PostDetail.vue
  src/hook/jobs/usePostDetailDeleteMutation.js
Labels: bug

#152 공고editor 유효성 검사 추가
  src/components/page/Hire/HirePostEditor.vue
Labels: enhancement

#154 Feat/#153
  components.d.ts
  src/api/Appicant/getApplicantListApi.js
  src/api/Appicant/getApplicantListApi2.js
  src/api/Appicant/getMDetailApi.js
  src/api/api.js
  src/api/qna/MyQnaDeleteDetailApi.js
  src/api/qna/MyQnaSaveDetailApi.js
  src/api/qna/MyQnaSearchDetailApi.js
  src/api/qna/qnaListSearchApi.js
  src/api/qna/updateMyQnaApi.js
  src/components/page/Applicant/ApplicantBody.vue
  src/components/page/Applicant/ApplicantResume.vue
  src/components/page/Applicant/ApplicantSearch2.vue
  src/components/page/Applicant/ApplicantStatusSearch.vue
  src/components/page/Qna/QnaDetailModal.vue
  src/components/page/Qna/QnaMain.vue
  src/components/page/Qna/QnaMyDetailModal.vue
  src/components/page/Qna/QnaPasswordCheckModal.vue
  src/components/page/Qna/QnaSerchWrite.vue
  src/hook/Applicant/useApllicantStatusUpdateMutation.js
  src/hook/Applicant/useGetApplicantListQUery.js
  src/hook/Applicant/useGetApplicantListQUery2.js
  src/hook/Applicant/useGetMDetailQuery.js
  src/hook/qna/MyQnaSearchDetailQuery.js
  src/hook/qna/useMyQnaDeleteMutation.js
  src/hook/qna/useMyqQnaSaveDetailMutation.js
  src/hook/qna/useQnaMyUpdateMutation.js
  src/router/index.js
  src/views/Applicant/ApplicantViewMain.vue
  src/views/Qna/QuesnAnsw.vue
Labels: bug

#158 기업정보 보기 tanstack query 적용 및 모듈화
  src/api/api.js
  src/api/company/companyDetailSearchApi.js
  src/components/page/Company/CompanyDetail.vue
  src/hook/company/useCompanyDetailSearchQuery.js
Labels: enhancement

#166 fix/#164 qna 기능 수정
  src/components/page/Qna/QnaMyDetailModal.vue
  src/components/page/Qna/QnaPasswordCheckModal.vue
Labels: bug

#168 Fix/#160 이력서 잔데이터 남는 현상 제거
  src/components/page/Apply/Resume/InnerPage/CareerList.vue
  src/components/page/Apply/Resume/InnerPage/CertList.vue
  src/components/page/Apply/Resume/InnerPage/EduList.vue
  src/components/page/Apply/Resume/InnerPage/SkillList.vue
Labels: bug

#169 feat:#167 css 적용
  components.d.ts
  src/components/common/ContextBox.vue
  src/components/common/Pagination.vue
  src/components/layout/AddOn.vue
  src/components/layout/LeftManuBar.vue
  src/components/layout/LeftManuBar_test.vue
  src/components/page/Approval/ApprovalPostMain.vue
  src/components/page/Approval/ConfirmedPostMain.vue
  src/components/page/Hire/HirePostMain.vue
  src/components/page/Jobs/Post/PostMain.vue
  src/components/page/Jobs/Scrap/ScrapMain.vue
  src/views/DashBoard/DashBoard.vue
Labels: enhancement

#171 지원자관리 구현
  components.d.ts
  src/components/page/Hire/HireApplicantMain.vue
  src/components/page/Hire/HirePostMain.vue
  src/components/page/Jobs/Post/PostDetail.vue
  src/router/index.js
  src/views/Hire/HireApplicant.vue
Labels: enhancement

#181 Fix/#160 개편된 UI에 맞춰 메뉴 추가 정단, 및 이력서 버그 수정
  src/components/layout/AddOn.vue
  src/components/layout/LeftManuBar.vue
  src/components/page/Apply/History/HistoryMain.vue
  src/components/page/Apply/Resume/InnerPage/ApplyInfo.vue
  src/components/page/Apply/Resume/InnerPage/CareerList.vue
  src/components/page/Apply/Resume/InnerPage/CertList.vue
  src/components/page/Apply/Resume/InnerPage/EduList.vue
  src/components/page/Apply/Resume/InnerPage/FileInfo.vue
  src/components/page/Apply/Resume/InnerPage/LinkInfo.vue
  src/components/page/Apply/Resume/InnerPage/SelfintroInfo.vue
  src/components/page/Apply/Resume/InnerPage/ShortintroInfo.vue
  src/components/page/Apply/Resume/InnerPage/SkillList.vue
  src/components/page/Apply/Resume/ResumeDetail.vue
  src/components/page/Apply/Resume/ResumeMain.vue
  src/views/Apply/History/History.vue
  src/views/Apply/Resume/Resume.vue
  src/views/DashBoard/DashBoard.vue
Labels: bug

#185 Feat/#61
  package-lock.json
  package.json
  src/api/faq/faqDetailDeleteApi.js
  src/api/faq/faqDetailInsertApi.js
  src/api/faq/faqDetailUpdateApi.js
  src/components/page/Board/Notice/NoticeDetail.vue
  src/components/page/Board/Notice/NoticeMain.vue
  src/components/page/Board/Notice/NoticeSearch.vue
  src/components/page/FAQ/FAQDetailModal.vue
  src/components/page/FAQ/FAQMain.vue
  src/hook/faq/useFAQDetailDelete.js
  src/hook/faq/useFAQDetailUpdate.js
Labels: bug

#186 회원관리 모달 오류 수정
  src/components/page/ManageUser/Applicant/ApplicantModal.vue
  src/components/page/ManageUser/Biz/BizModal.vue
Labels: bug

#188 feat:#175 스크랩 페이지 새로 고침
  components.d.ts
  src/components/page/Jobs/Post/PostApplyModal.vue
  src/components/page/Jobs/Post/PostDetail.vue
Labels: bug

#191 feat/#61 css 최종본
  components.d.ts
  src/components/page/Board/Notice/NoticeDetail.vue
Labels: enhancement

#192 feat:#190 console.log / alert 변경
  src/api/Appicant/ApplicantResumeListApi.js
  src/api/Appicant/getApplicantListApi.js
  src/api/Appicant/getApplicantPaginApi.js
  src/api/Appicant/getMDetailApi.js
  src/api/Appicant/updateApplicantStatusApi.js
  src/api/jobs/postDetailApplyApi.js
  src/api/jobs/postDetailDeleteApi.js
  src/api/manageUser/applicantDetailUpdateApi.js
  src/api/manageUser/bizDetailUpdateApi.js
  src/api/mypage/deleteUserApi.js
  src/api/mypage/updatePwdApi.js
  src/api/qna/AsIsqnaListSearchApi.js
  src/api/qna/MyQnaSaveDetailApi.js
  src/api/qna/MyQnaSearchDetailApi.js
  src/api/qna/qnaListSearchApi.js
  src/api/qna/updateMyQnaApi.js
  src/common/nullCheck.js
  src/components/page/Applicant/ApplicantBody.vue
  src/components/page/Applicant/ApplicantResume.vue
  src/components/page/Board/Notice/NoticeDetail.vue
  src/components/page/FAQ/FAQDetailModal.vue
  src/components/page/Hire/HireApplicantMain.vue
  src/components/page/Hire/HirePostEditor.vue
  src/components/page/Jobs/Post/PostApplyModal.vue
  src/components/page/Jobs/Post/PostDetail.vue
  src/components/page/Jobs/Scrap/ScrapSearch.vue
  src/components/page/MyPage/UpdatePwdModal.vue
  src/components/page/Qna/AsIsQnaDetailModal.vue
  src/components/page/Qna/AsIsQnaMain.vue
  src/components/page/Qna/AsIsQnaSerchWrite.vue
  src/components/page/Qna/QnaDetailModal.vue
  src/components/page/Qna/QnaMain.vue
  src/components/page/Qna/QnaMyDetailModal.vue
  src/components/page/Qna/QnaPasswordCheckModal.vue
  src/components/page/Qna/QnaSerchWrite.vue
  src/hook/jobs/usePostUpdateStatusMutation.js
  src/hook/jobs/useScrapUpdateMutation.js
  src/hook/manageUser/useApplicantDetailUpdateMutation.js
  src/hook/manageUser/useBizDetailUpdateMutation.js
  src/hook/qna/useMyQnaDeleteMutation.js
  src/hook/qna/useMyqQnaSaveDetailMutation.js
  src/hook/qna/useQnaMyUpdateMutation.js
Labels: documentation

#193 라우터 수정
  src/router/index.js
Labels: bug

#195 Fix/#160 통합테스트 피드백 4개 수정 완료료
  package-lock.json
  src/components/page/Apply/History/HistoryMain.vue
  src/components/page/Apply/Resume/InnerPage/CareerList.vue
  src/components/page/Apply/Resume/InnerPage/CertList.vue
  src/components/page/Apply/Resume/InnerPage/EduList.vue
  src/components/page/Apply/Resume/InnerPage/SkillList.vue
  src/components/page/Apply/Resume/ResumeDetail.vue
  src/components/page/Apply/Resume/ResumeMain.vue
  src/components/page/Board/Notice/NoticeSearch.vue
  src/components/page/MyPage/MyPageMain.vue
  src/hook/jobs/useScrapUpdateMutation.js
Labels: bug

#197 fix/#196 qna 수정
  src/components/page/FAQ/FAQDetailModal.vue
  src/components/page/Qna/QnaDetailModal.vue
  src/components/page/Qna/QnaMain.vue
  src/components/page/Qna/QnaMyDetailModal.vue
  src/components/page/Qna/QnaPasswordCheckModal.vue
Labels: bug
